baseURL = 'https://chongliujia.github.io'
languageCode = 'en-us'
title = "Chongliu's blog"
description = "The blog is my learning notes"
theme = 'PaperMod'

tags = [
  "blog",
  "search",
]

features = [
  "blog",
  "search",
]
